In [35]:
import numpy 
import math
import random
a = numpy.zeros((10, 10))
ang = [i * 10 for i in range(36)]
print(a)
for i in range(10):
    for j in range(10):
        a[i]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
def argument(a):
    return math.atan2(a.imag, a.real) * 180 / math.pi

In [37]:
def module(a):
    return math.sqrt(a.real ** 2 + a.imag **2)

In [38]:
def diff(a, b):
    z = complex(a) + complex(b)
    return module(z)

In [39]:
def torm(a, b):
    return module(a) + module(b)

In [40]:
def angle():
    return random.uniform(ang)

In [41]:
angle()

TypeError: uniform() missing 1 required positional argument: 'b'